- hosts: localhost
  gather_facts: no
  vars:
    gns3_url: "http://192.168.56.1"
  collections:
    - davidban77.gns3
  tasks:
    - name: "Verify version of GNS3 server"
      gns3_version:
        url: "{{ gns3_url }}"
      register: version
    - debug: var=version

