- hosts: localhost
  gather_facts: no
  vars:
    gns3_url: "http://192.168.56.1"
    gns3_nodes_spec:
      - name: "dht1"
        template: " "
      - name: "dht2"
        template: "opendht-alpine"
      - name: "switch"
        template: "Ethernet switch"
      - name: "cloud"
        template: "Cloud"

    gns3_links_spec:
      - ["dht1", "eth0", "switch", "e0"]
      - ["dht2", "eth0", "switch", "e1"]
      - ["switch", "e2", "cloud", "eth1"]
  collections:
    - davidban77.gns3
  tasks:
    - name: "Create network topology"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "demo_lab"
        state: present
        nodes_spec: "{{ gns3_nodes_spec }}"
        links_spec: "{{ gns3_links_spec }}"

    - name: "Start nodes"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "demo_lab"
        state: opened
        nodes_state: started
        nodes_strategy: one_by_one

